### PR TITLE
Beginning of the Bohemia rework, currently redone the German tags and changed the markets+overlords to be more like FF

### PR DESCRIPTION
**Pull request by Netgearghost**

### CODE REVIEW

**Review by MadJamez — COMMENTED** [review]
It seems alot of minor german nations are not possible to reach their market. Also bavarian market seems to be dying and missing some goods.
image

Just wondering, but what did you change in the provinces.png?

**Comment by Netgearghost** [comment]
I expanded Frankfurt a little bit, and split up the province that originally holds the city of Nuremberg to about 3 new provinces, controlled be Bavaria, Ansbach, and Bayreuth. I also slightly changed around the provinces in saxony to give them better shape. 

As for the markets, either we put Bavaria in Bohemia’s market or leave them be. Nations don’t always have to have every good. As for Hesse-Kassel, this is a problem with the base game; ie Luxemburg. They won’t actually impact sell/buy orders for that market and will operate as “isolated states”. Or, we just throw them in Burgundy’s market

**Comment by Netgearghost** [comment]
Oh and Ulm’s province got slightly expanded too so it borders Bavaria.

**Comment by Xerodoeht** [comment]
If you can't figure out the trade routes I can help you with them

**Comment by Netgearghost** [comment]
Sure, I will have a look tomorrow. I’ve still got to do historical buildings for all these new tags too. I’ve been holding off on that though since I’m unsure how it’s been ported over in the past

**Review by Xerodoeht — APPROVED** [review]

**Pull request merged**
